version: '3'
services:
  mongo:
    container_name: maps_mongo
    image: mongo:3.4.2
    ports:
      - 27017:27017
    environment:
      MONGODB_USERNAME: mongo_user
      MONGODB_PASSWORD: 12345

  node:
    container_name: maps_node
    image: node:7.7.4
    stdin_open: true
    tty: true
    volumes:
      - ../app:/var/www
      - ../node_modules:/node_modules
      - ../package.json:/package.json
      - ../yarn.lock:/yarn.lock
    depends_on:
      - mongo

  nginx:
    container_name: maps_nginx
    image: nginx:1.11
    ports:
      - 80:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx
      - ./logs:/etc/nginx/logs
    depends_on:
      - node
